version: '2.2'
services:
  hola:
    build:
      context: ./
      dockerfile: Dockerfile
    image: document-api
    ports:
      - 8080
    networks:
      - network1
    scale: 2

networks:
  network1: